version: '3'

services:
  postgres_dev:
    container_name: 'postgres-dev'
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres

  mailcatcher:
    container_name: mailcatcher
    image: sj26/mailcatcher
    expose:
      - '1025'
      - '1080'
    ports:
      - '1025:1025'
      - '1080:1080'

volumes:
  postgres_data: