[default]
DEBUG = false
TITLE = "Landpage"
SQLALCHEMY_DATABASE_URI = 'postgresql://local_user:local_password@localhost:5432/local_db'
SECRET_KEY = "jadkfbsdkjbfbh"
EXTENSIONS = [
    "landpage.blueprints.webui:init_app",
    "landpage.ext.database:init_app",
    "landpage.ext.commands:init_app",
]
